/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_grgbanking_driverlibs_nativeUtil */

#ifndef _Included_com_grgbanking_driverlibs_nativeUtil
#define _Included_com_grgbanking_driverlibs_nativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_grgbanking_driverlibs_nativeUtil
 * Method:    test
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_grgbanking_driverlibs_nativeUtil_test
        (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_grgbanking_driverlibs_nativeUtil
 * Method:    getnumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_grgbanking_driverlibs_nativeUtil_getnumber
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
